<GameLayout>:
  canvas:
    Rectangle:
      source: 'monster-background.png'
      size: self.size

  StickerBookBar:
    size_hint: .08, .7
    pos_hint: {'center_x': .05, 'center_y': .5}

  Sticker:
    source: 'monster01.png'
    height: 300
    width: 300


<StickerBookBar>:
  canvas:
    Color:
      rgba: 1, 1, 0, .8
    Rectangle:
      size: self.size

<StickerBookBarButton>:
  canvas:
    Color:
      rgb: 1, 0, 1
  text: 'X'
  height: 100

<Sticker>:


<GameMenu>:

